import type { INodeProperties } from "n8n-workflow";

export const updateAddressDescription: INodeProperties[] = [
  {
    displayName: "Address ID",
    name: "addressId",
    type: "number",
    required: true,
    displayOptions: {
      show: {
        resource: ["address"],
        operation: ["update"],
      },
    },
    default: 0,
    description: "The ID of the address to update",
  },
  {
    displayName: "Additional Fields",
    name: "additionalFields",
    type: "collection",
    placeholder: "Add Field",
    default: {},
    displayOptions: {
      show: {
        resource: ["address"],
        operation: ["update"],
      },
    },
    options: [
      {
        displayName: "Anrede",
        name: "Anrede",
        type: "options",
        options: [
          { name: "Eheleute", value: "Eheleute" },
          { name: "Familie", value: "Familie" },
          { name: "Firma", value: "Firma" },
          { name: "Frau", value: "Frau" },
          { name: "Herr", value: "Herr" },
        ],
        default: "Herr",
      },
      {
        displayName: "Betreuer",
        name: "Benutzer",
        type: "string",
        default: "",
        description: "User name of the support person",
      },
      {
        displayName: "E-Mail",
        name: "email",
        type: "string",
        placeholder: "name@email.com",
        default: "",
      },
      {
        displayName: "Firma",
        name: "Zusatz1",
        type: "string",
        default: "",
      },
      {
        displayName: "Geschlecht",
        name: "Geschlecht",
        type: "string",
        default: "",
      },
      {
        displayName: "Herkunft Kontakt",
        name: "HerkunftKontakt",
        type: "options",
        options: [
          { name: "Eigene Webseite", value: "webseite_system" },
          { name: "Empfehlung", value: "Empfehlung" },
          { name: "Flyer", value: "Flyer" },
          { name: "ImmoScout24", value: "immobilienscout24_system" },
          { name: "Suchmaschine", value: "Suchmaschine" },
        ],
        default: "webseite_system",
      },
      {
        displayName: "Homepage",
        name: "Homepage",
        type: "string",
        default: "",
      },
      {
        displayName: "Kontaktart",
        name: "ArtDaten",
        type: "multiOptions",
        options: [
          { name: "Eigentümer", value: "Eigentümer" },
          { name: "Interessent Kauf", value: "Interessent Kauf" },
          { name: "Interessent Miete", value: "Interessent Miete" },
          { name: "Investor", value: "Investor" },
          { name: "Kooperationspartner", value: "Kooperationspartner" },
          { name: "Kunde", value: "Kunde" },
          { name: "Makler", value: "Makler" },
          { name: "Notar", value: "Notar" },
          { name: "Privatkontakt", value: "Privatkontakt" },
          { name: "Tippgeber", value: "Tippgeber" },
        ],
        default: [],
      },
      {
        displayName: "Land",
        name: "Land",
        type: "string",
        default: "Deutschland",
      },
      {
        displayName: "Name",
        name: "Name",
        type: "string",
        default: "",
      },
      {
        displayName: "Newsletter",
        name: "newsletter_aktiv",
        type: "options",
        options: [
          { name: "No", value: 0 },
          { name: "Yes", value: 1 },
          { name: "Cancellation", value: 2 },
          { name: "Double Opt-in Pending", value: 3 },
          { name: "Not Specified", value: 4 },
        ],
        default: 0,
      },
      {
        displayName: "Ort",
        name: "Ort",
        type: "string",
        default: "",
      },
      {
        displayName: "PLZ",
        name: "Plz",
        type: "string",
        default: "",
      },
      {
        displayName: "Status",
        name: "Status",
        type: "options",
        options: [
          { name: "Active", value: 1 },
          { name: "Archive", value: 0 },
        ],
        default: 1,
      },
      {
        displayName: "Straße",
        name: "Strasse",
        type: "string",
        default: "",
      },
      {
        displayName: "Telefonnummer",
        name: "phone_private",
        type: "string",
        default: "",
      },
      {
        displayName: "Vorname",
        name: "Vorname",
        type: "string",
        default: "",
      },
    ],
  },
];
