import type { INodeProperties } from "n8n-workflow";

export const createAddressDescription: INodeProperties[] = [
	{
		displayName: "Additional Fields",
		name: "additionalFields",
		type: "collection",
		placeholder: "Add Field",
		default: {},
		displayOptions: {
			show: {
				resource: ["address"],
				operation: ["create"],
			},
		},
		options: [
			{
				displayName: "Anrede",
				name: "Anrede",
				type: "options",
				options: [
					{ name: "Eheleute", value: "Eheleute" },
					{ name: "Familie", value: "Familie" },
					{ name: "Firma", value: "Firma" },
					{ name: "Frau", value: "Frau" },
					{ name: "Herr", value: "Herr" },
				],
				default: "Herr",
			},
			{
				displayName: "Betreuer",
				name: "Benutzer",
				type: "string",
				default: "",
			},
			{
				displayName: "Body",
				name: "body",
				type: "string",
				default: "",
				description: "Email content. Ignored if templateid has a valid value.",
			},
			{
				displayName: "Check Duplicate",
				name: "checkDuplicate",
				description:
					"Whether a duplicate check is performed for the field “email”. Without the parameter noOverrideByDuplicate, the data of the already existing address is updated or overwritten.",
				type: "boolean",
				default: false,
			},
			{
				displayName: "Dokumentattributes",
				name: "documentattributes",
				type: "string",
				default: "",
				description: "Field names of the document attributes",
			},
			{
				displayName: "E-Mail",
				name: "email",
				type: "string",
				placeholder: "name@email.com",
				default: "",
			},
			{
				displayName: "Estate IDs",
				name: "estateids",
				type: "string",
				default: "",
				description: "Database IDs of estates in enterprise",
			},
			{
				displayName: "Firma",
				name: "Zusatz1",
				type: "string",
				default: "",
			},
			{
				displayName: "Geschlecht",
				name: "Geschlecht",
				type: "string",
				default: "",
			},
			{
				displayName: "Herkunft Kontakt",
				name: "HerkunftKontakt",
				type: "options",
				options: [
					{ name: "Eigene Webseite", value: "webseite_system" },
					{ name: "Empfehlung", value: "Empfehlung" },
					{ name: "Flyer", value: "Flyer" },
					{ name: "ImmoScout24", value: "immobilienscout24_system" },
					{ name: "Suchmaschine", value: "Suchmaschine" },
				],
				default: "webseite_system",
			},
			{
				displayName: "Homepage",
				name: "Homepage",
				type: "string",
				default: "",
			},
			{
				displayName: "Kontaktart",
				name: "ArtDaten",
				type: "multiOptions",
				options: [
					{ name: "Eigentümer", value: "Eigentümer" },
					{ name: "Interessent Kauf", value: "Interessent Kauf" },
					{ name: "Interessent Miete", value: "Interessent Miete" },
					{ name: "Investor", value: "Investor" },
					{ name: "Kooperationspartner", value: "Kooperationspartner" },
					{ name: "Kunde", value: "Kunde" },
					{ name: "Makler", value: "Makler" },
					{ name: "Notar", value: "Notar" },
					{ name: "Privatkontakt", value: "Privatkontakt" },
					{ name: "Tippgeber", value: "Tippgeber" },
				],
				default: [],
			},
			{
				displayName: "Kontaktkategorie",
				name: "contactCategory",
				type: "options",
				options: [
					{ name: "Dachverband", value: "umbrellaOrganization" },
					{ name: "Eheleute", value: "marriedCouple" },
					{ name: "Eigentümergemeinschaft", value: "communityOfOwners" },
					{ name: "Erbengemeinschhaft", value: "communityOfHeirs" },
					{ name: "Geschäftskunde", value: "businessCustomer" },
					{ name: "Geschäftsstelle", value: "branch" },
					{ name: "Institution", value: "institution" },
					{ name: "Privatkunde", value: "privateCustomer" },
					{ name: "Unternehmen", value: "company" },
					{ name: "Verein", value: "association" },
				],
				default: "privateCustomer",
			},
			{
				displayName: "Land",
				name: "Land",
				type: "string",
				default: "Deutschland",
			},
			{
				displayName: "Message ID",
				name: "messageid",
				type: "string",
				default: "",
				description:
					"Message ID of an existing email. Used together with parameters forwarded or replied to forward or reply to this email.",
			},
			{
				displayName: "Name",
				name: "Name",
				type: "string",
				default: "",
			},
			{
				displayName: "Newsletter",
				name: "newsletter_aktiv",
				type: "options",
				options: [
					{ name: "No", value: 0 },
					{ name: "Yes", value: 1 },
					{ name: "Cancellation", value: 2 },
					{ name: "Double Opt-in Pending", value: 3 },
					{ name: "Not Specified", value: 4 },
				],
				default: 0,
			},
			{
				displayName: "No Override By Duplicate",
				name: "noOverrideByDuplicate",
				description:
					"Whether duplicate check with parameter checkDuplicate does not update or overwrite the data of the already existing address",
				type: "boolean",
				default: false,
			},
			{
				displayName: "Online Attachment IDs",
				name: "onlineattachmentids",
				type: "string",
				default: "",
				description: "The IDs of the estate files from the files tab",
			},
			{
				displayName: "Ort",
				name: "Ort",
				type: "string",
				default: "",
			},
			{
				displayName: "PDF Exposé ID",
				name: "pdfexposeidentifiers",
				type: "string",
				default: "",
				description: "Identifiers for PDF exposés",
			},
			{
				displayName: "PDF Form IDs",
				name: "pdfformids",
				type: "string",
				default: "",
				description: "IDs of the PDF forms sent as attachments",
			},
			{
				displayName: "PDF Letter IDs",
				name: "pdfletterids",
				type: "string",
				default: "",
				description: "IDs of the PDF letters sent as attachments",
			},
			{
				displayName: "PLZ",
				name: "Plz",
				type: "string",
				default: "",
			},
			{
				displayName: 'Reply To',
				name: "replyto",
				type: "string",
				default: "",
				description: "Email address for email reply",
			},
			{
				displayName: "Straße",
				name: "Strasse",
				type: "string",
				default: "",
			},
			{
				displayName: "Subject",
				name: "subject",
				type: "string",
				default: "",
				description: "Email subject",
			},
			{
				displayName: "Telefonnummer",
				name: "phone_private",
				type: "string",
				default: "",
			},
			{
				displayName: "Template ID",
				name: "templateid",
				type: "string",
				default: "",
				description: "ID of an email template stored in enterprise",
			},
			{
				displayName: "Vorname",
				name: "Vorname",
				type: "string",
				default: "",
			},
		],
	},
];
